bugzilla_credentials:
  bugzilla_uri:
  username:
  password:
github_credentials:
  username:
  password:
commit_monitor:
  bugzilla_product:
gem_changes_labeler:
  enabled_repos: []
github_notification_monitor:
  repo_names: []
travis_event:
  enabled_repos: []
